apiVersion: v1
kind: ReplicaSet
metadata:
  name: replicaset
  label: backend
spec:
  template:  
    metadata:
      name: mscloud
      lebals:
        app: web-app-pod
        layer: frontend
        
    spec:
      containers:              # container is a list
        - name: dev_container
          image: nginx

  replicas: 4
  selector:      # helps us to filter pods tat have a particular tag i.e same label as the pod
    matchLabels: 
      layer: frontend              


      #commands
      # kubectl create -f pods/pod.yaml
      # kubectl get pods
      # kubectl get rs
      # every pod will have an ip addresss.

      #kubectl delete replicaset